#!/bin/bash

export KUBECONFIG="$(./bin/kind get kubeconfig-path --name=k8stest)"

if [ ! -f success ]; then
   ./bin/kubectl -nspire logs deployment/spire-server --all-containers || true
   ./bin/kubectl -nspire logs daemonset/spire-agent --all-containers || true
   ./bin/kubectl -nspire logs deployment/example-workload --all-containers || true
fi

export KUBECONFIG=
./bin/kind delete cluster --name k8stest
