ServerAddress = "127.0.0.1"
ServerPort = "8080"
TrustDomain = "example.com"
TrustBundlePath = ".conf/bundle.pem"

BindAddress = "127.0.0.1"
BindPort = "8081"
DataDir = "."
PluginDir = "../../plugin/agent/.conf"
LogFile = "spire-server.log"
LogLevel = "INFO"
