ServerAddress = "127.0.0.1"
ServerPort = "8081"
TrustDomain = "localhost"
TrustBundlePath = ".conf/bundle.pem"

BindAddress = "127.0.0.1"
BindPort = "8088"
DataDir = "."
PluginDir = "../../plugin/agent/.conf"
LogLevel = "INFO"
