#!/bin/bash

log-info "Checking CipherTrust KMS Signing Service..."

sleep 2

if docker-compose logs spire-server | grep -q "Signature received from CipherTrust"; then
  log-info "SVID Signature generated successfully."
else
  fail-now "Signature failed."
fi
