#!/bin/bash

log-info "Checking Server SVID Bootstrap..."

sleep 2

if docker-compose logs spire-server | grep -q "Signed X509 SVID"; then
  log-info "Server SVID Signed with the Thales CipherTrust Key Manager."
else
  fail-now "Server SVID signature failed."
fi
