#!/bin/bash

log-debug "agent re-attesting..."

# Check at most 30 times (with one second in between) that the agent is able to re-attest
MAXCHECKS=30
CHECKINTERVAL=1
for ((i=1;i<=MAXCHECKS;i++)); do
    log-info "checking for agent to get notification and try to reattest ($i of $MAXCHECKS max)..."
    docker compose logs spire-agent
    if docker compose logs spire-agent | grep "Agent needs to re-attest; will attempt to re-attest"; then
	    exit 0
    fi
    sleep "${CHECKINTERVAL}"
done

# Check at most 30 times (with one second in between) that the agent has re-attested
MAXCHECKS=30
CHECKINTERVAL=1
for ((i=1;i<=MAXCHECKS;i++)); do
    log-info "checking for agent to get notification and try to reattest ($i of $MAXCHECKS max)..."
    docker compose logs spire-agent
    if docker compose logs spire-agent | grep "Successfully reattested node"; then
	    exit 0
    fi
    sleep "${CHECKINTERVAL}"
done

fail-now "timed out waiting for agent to re-attest"
