#!/bin/bash

log-debug "deleting agent..."

docker-compose exec -T spire-server \
    /opt/spire/bin/spire-server agent evict \
    -spiffeID "spiffe://domain.test/spire/agent/x509pop/$(fingerprint conf/agent/agent.crt.pem)"

# Check at most 30 times (with one second in between) that the agent is going to shut down
MAXCHECKS=30
CHECKINTERVAL=1
for ((i=1;i<=MAXCHECKS;i++)); do
    log-info "checking for agent to get notification and try to reattest ($i of $MAXCHECKS max)..."
    docker-compose logs spire-agent
    if docker-compose logs spire-agent | grep "Agent needs to re-attest; removing SVID and shutting down"; then
	exit 0
    fi
    sleep "${CHECKINTERVAL}"
done

fail-now "timed out waiting for agent to shut down"
