#!/bin/bash

# Verify that the bundle exposes WIT authorities when the WIT profile is enabled
docker compose exec -T spire-server /opt/spire/bin/spire-server bundle show -output json | jq -e '.wit_authorities | length != 0' || fail-now "wit_authorities should have been non-empty"
