#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PKGDIR="${REPODIR}/pkg/server/datastore"

log-debug "building cassandra test harness..."
(cd "${PKGDIR}"; go test -c -o "${DIR}"/cassandra.test -ldflags '-X github.com/spiffe/spire/pkg/server/datastore_test.TestDialect=cassandra -X github.com/spiffe/spire/pkg/server/datastore_test.TestConnString=["localhost:9053"];spire_test')

log-debug "copying over test data..."
cp -r "${PKGDIR}"/testdata .
