#!/bin/bash

source init-kubectl

#1 - namespace
#2 - app_name
#3 workload spiffeID
add_entry_for_workload() {
    ns=$1
    app_name=$2
    workload_spiffe_id=$3
    SERVER_POD=$(${KUBEBIN} -n${ns} get pod -l app=spire-server -o jsonpath="{.items[0].metadata.name}")
    CLUSTERNODESPIFFEID="spiffe://example.org/k8s-workload-registrar/example-cluster/node"
    WORKLOAD_POD=$(${KUBEBIN} -n${ns} get pod -l app=${app_name} -o jsonpath="{.items[0].metadata.name}")
    if ${KUBEBIN} -n${ns} exec ${SERVER_POD} -- /opt/spire/bin/spire-server entry create \
    -spiffeID ${workload_spiffe_id} \
    -parentID ${CLUSTERNODESPIFFEID} \
    -selector k8s:image-signature-subject:hpespirex@gmail.com \
    -selector k8s:ns:${ns} \
    -selector k8s:pod-name:${WORKLOAD_POD} ;then
        return
    fi
    fail-now "Failed creating entry for workload "
}

add_entry_for_workload spire example-workload-signed spiffe://example.org/ns/default/sa/default/workload-signed
add_entry_for_workload spire example-workload-unsigned spiffe://example.org/ns/default/sa/default/workload-unsigned
add_entry_for_workload spire example-workload-signed-wrong-subject spiffe://example.org/ns/default/sa/default/workload-signed-wrong-subject

add_entry_for_workload_with_extra_selectors() {
    ns=$1
    app_name=$2
    workload_spiffe_id=$3
    signature_content=$4
    logid=$5
    integrated_time=$6
    SERVER_POD=$(${KUBEBIN} -n${ns} get pod -l app=spire-server -o jsonpath="{.items[0].metadata.name}")
    CLUSTERNODESPIFFEID="spiffe://example.org/k8s-workload-registrar/example-cluster/node"
    WORKLOAD_POD=$(${KUBEBIN} -n${ns} get pod -l app=${app_name} -o jsonpath="{.items[0].metadata.name}")
    if ${KUBEBIN} -n${ns} exec ${SERVER_POD} -- /opt/spire/bin/spire-server entry create \
    -spiffeID ${workload_spiffe_id} \
    -parentID ${CLUSTERNODESPIFFEID} \
    -selector k8s:image-signature-subject:hpespirex@gmail.com \
    -selector k8s:image-signature-content:${signature_content} \
    -selector k8s:image-signature-logid:${logid} \
    -selector k8s:image-signature-integrated-time:${integrated_time} \
    -selector k8s:ns:${ns} \
    -selector k8s:pod-name:${WORKLOAD_POD} ;then
        return
    fi
    fail-now "Failed creating extra entry for workload "
}

add_entry_for_workload_with_extra_selectors spire example-workload-signed-extra spiffe://example.org/ns/default/sa/default/workload-signed-extra MEUCIG6n/ocQSOvznvs/Co/tmp5tY5tDb4Zl+3un5X+whQddAiEA4mHVOBBT9XW086M2dM8RyjutBdMrJxcJB5wHYFyzzzs= c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d 1638297518
