#!/bin/sh

source init-kubectl
source check_for_workload_svid

check_for_workload_svid "spiffe://example.org/ns/default/sa/default/workload-unsigned" example-workload-unsigned

if [ "${DONE}" -eq 1 ]; then
    log-info "SPIFFE ID found for unsigned image in skip list."
elif [ "${DONE}" -eq 0 ]; then
    fail-now "timed out waiting for workload to obtain credentials."
else
    fail-now "failed to check for svid"
fi
