run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 12m

issues:
  exclude-dirs:
    - testdata$
    - test/mock
  exclude-files:
    - ".*\\.pb\\.go"

linters:
  enable:
    - bodyclose
    - durationcheck
    - errorlint
    - goimports
    - revive
    - gosec
    - misspell
    - nakedret
    - unconvert
    - unparam
    - whitespace
    - gocritic
    - nolintlint

linters-settings:
  revive:
    # minimal confidence for issues, default is 0.8
    confidence: 0.0
    rules:
      - name: unused-parameter
        disabled: true
