run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 12m

  skip-dirs:
    - testdata$
    - test/mock

  skip-files:
    - ".*\\.pb\\.go"
    - support/k8s/k8s-workload-registrar/mode-crd/api/spiffeid/v1beta1/spiffeid_types.go

linters:
  enable:
    - bodyclose
    - depguard
    - durationcheck
    - errorlint
    - goimports
    - revive
    - gosec
    - misspell
    - nakedret
    - unconvert
    - unparam
    - whitespace
    - gocritic
    # nolintlint can be re-enabled after the rest of the linters have gained
    # support for go1.18.
    # - nolintlint
linters-settings:
  revive:
    # minimal confidence for issues, default is 0.8
    confidence: 0.0
