version: "2"
run:
  timeout: 12m
linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - exptostd
    - gocritic
    - gosec
    - intrange
    - mirror
    - misspell
    - nakedret
    - nilnesserr
    - nolintlint
    - predeclared
    - reassign
    - revive
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  settings:
    govet:
      enable:
        - sortslice
        - unusedwrite
    revive:
      confidence: 0
      rules:
        - name: atomic
        - name: bool-literal-in-expr
        - name: constant-logical-expr
        - name: context-as-argument
        - name: datarace
        - name: error-naming
        - name: error-return
        - name: errorf
        - name: increment-decrement
        - name: modifies-value-receiver
        - name: receiver-naming
        - name: string-of-int
        - name: time-equal
        - name: unreachable-code
        - name: use-any
        - name: useless-break
    staticcheck:
      checks:
        - all
        - -ST1003
        - -QF1001
        - -QF1008
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: (.*_test\.go$)|(^test/.*)
        text: integer overflow conversion
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
