run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 12m

issues:
  exclude-dirs:
    - testdata$
    - test/mock
  exclude-files:
    - ".*\\.pb\\.go"

linters:
  enable:
    - bodyclose
    - durationcheck
    - errorlint
    - gofmt
    - goimports
    - revive
    - gosec
    - misspell
    - nakedret
    - nilerr
    - unconvert
    - unparam
    - intrange
    - whitespace
    - gocritic
    - copyloopvar
    - wastedassign
    - nolintlint

linters-settings:
  govet:
    enable:
      - nilness
      - sortslice
      - unusedwrite
  revive:
    # minimal confidence for issues, default is 0.8
    confidence: 0.0
    rules:
      - name: unused-parameter
        disabled: true
