#!/bin/bash

RETRIES=10
AGENTFOUND=0
HEALTHCHECK=0
HEALTHCHECKFAIL=0

for ((m=1;m<=$RETRIES;m++)); do

    AGENTS=$(docker-compose exec -T spire-server /opt/spire/bin/spire-server agent list)
    if [ "$AGENTS" != "No attested agents found" ]; then
        AGENTFOUND=1  
        break
    fi

done

HEALTH=$(docker-compose exec -T spire-agent /opt/spire/bin/spire-agent healthcheck)
HEALTHFAIL=$(docker-compose exec -T spire-agent /opt/spire/bin/spire-agent healthcheck -socketPath invalid/path 2>&1 &)

if [[ "$HEALTH" =~ "Agent is healthy." ]]; then
    HEALTHCHECK=1
fi

if [[ "$HEALTHFAIL" =~ "Agent is unhealthy: unable to determine health" ]]; then
    HEALTHCHECKFAIL=1
fi

if [ $AGENTFOUND -eq 1 ] && [ $HEALTHCHECK -eq 1 ] && [ $HEALTHCHECKFAIL -eq 1 ]; then
    exit 0
else
    exit 1
fi
