#!/bin/bash

RETRIES=10
AGENTFOUND=0
VALIDCONFIG=0
INVALIDCONFIG=0

for ((m=1;m<=$RETRIES;m++)); do

    AGENTS=$(docker-compose exec -T spire-server /opt/spire/bin/spire-server agent list)
    if [ "$AGENTS" != "No attested agents found" ]; then
        AGENTFOUND=1  
        break
    fi

done

VALIDATE=$(docker-compose exec -T spire-agent /opt/spire/bin/spire-agent validate)
VALIDATEFAIL=$(docker-compose exec -T spire-agent /opt/spire/bin/spire-agent validate -config invalid/path 2>&1 &)

if [[ "$VALIDATE" =~ "SPIRE agent configuration file is valid." ]]; then
    VALIDCONFIG=1
fi

if [[ "$VALIDATEFAIL" =~ "SPIRE agent configuration file is invalid" ]]; then
    INVALIDCONFIG=1
fi

if [ $AGENTFOUND -eq 1 ] && [ $VALIDCONFIG -eq 1 ] && [ $INVALIDCONFIG -eq 1 ]; then
    exit 0
else
    exit 1
fi
