#!/bin/bash

docker-up old-spire-server

log-debug "bootstrapping old agent..."
docker-compose exec -T old-spire-server \
    /opt/spire/bin/spire-server bundle show > conf/agent/bootstrap.crt

docker-up old-spire-agent
