#!/bin/bash

MAXCHECKS=15
CHECKINTERVAL=3

# Keep dumping the SVID until we've detected a rotation
for ((i=1;i<=MAXCHECKS;i++)); do
    log-info "checking X509-SVID after server upgrade ($i of $MAXCHECKS max)..."
    docker-compose exec -T old-spire-agent \
        /opt/spire/bin/spire-agent api fetch x509 \
        -write /opt/test/after-server-upgrade || fail-now "SVID check failed"
    if ! cmp --silent svids/before-server-upgrade/svid.0.pem svids/after-server-upgrade/svid.0.pem; then
        # SVID has rotated
        exit 0
    fi
    sleep "${CHECKINTERVAL}"
done

fail-now "Timed out waiting for the SVID to rotate after upgrading the server"
