#!/bin/bash

log-info "checking X509-SVID after agent upgrade..."
docker-compose exec new-spire-agent \
    /opt/spire/bin/spire-agent api fetch x509 \
    -write /opt/test/after-agent-upgrade || fail-now "SVID check failed"

# SVIDs are cached in agent memory only. As the agent was restarted, there
# is no reason to believe that the SVID should compare the same. We'll do
# the comparison anyway as a sanity check.
if cmp --silent svids/after-server-upgrade/svid.0.pem svids/after-agent-upgrade/svid.0.pem; then
    fail-now "SVID comparison failed unexpectedly after agent restart"
fi
