#!/bin/sh

source init-kubectl
source check_for_workload_svid

check_for_workload_svid "spiffe://example.org/ns/spire/sa/example-workload-unsigned" example-workload-unsigned

if [ "${DONE}" -eq 0 ]; then
    log-info "No SPIFFE ID with subject selector provided for unsigned image."
elif [ "${DONE}" -eq 1 ]; then
    fail-now "Unexpected SPIFFE ID with subject selector provided for unsined image"
else
    fail-now "failed to check for svid"
fi
