#!/bin/sh

source init-kubectl
source check_for_workload_svid

check_for_workload_svid "spiffe://example.org/ns/spire/sa/example-workload-signed-wrong-subject" example-workload-signed-wrong-subject

if [ "${DONE}" -eq 0 ]; then
    log-info "No SPIFFE ID with subject selector provided for the image."
elif [ "${DONE}" -eq 1 ]; then
    fail-now "Unexpected SPIFFE ID with subject selector provided for the image"
else
    fail-now "failed to check for svid"
fi
