#!/bin/bash
source ./common

docker-up spire-agent

create-service spire-agent C:/spire/bin/spire-agent.exe
start-service spire-agent run -config C:/spire/conf/agent/agent.conf
assert-service-status spire-agent RUNNING
