#!/bin/bash

# Test downstream workload
docker-compose exec -u 1001 -T spire-agent \
	/opt/spire/conf/agent/downstreamclient || fail-now "fail to check downstream endpoints"

# Test regular workload
docker-compose exec -u 1002 -T spire-agent \
	/opt/spire/conf/agent/downstreamclient -expectErrors || fail-now "fail to check permission errors on downstream endpoints"
