#!/bin/bash
echo ${ROOTDIR}
"${ROOTDIR}/setup/x509pop/setup.sh" conf/server conf/ # Throw the agent cert in conf/, it is unused
"${ROOTDIR}/setup/node-attestation/build.sh" "${RUNDIR}/conf/server/node-attestation"
"${ROOTDIR}/setup/node-attestation/build.sh" "${RUNDIR}/conf/agent/node-attestation"

