#!/bin/bash

# Run success cases
docker-compose exec -u 1001 -T spire-agent \
	/opt/spire/conf/agent/adminclient || fail-now "fail to check admin endpoints"

# Run cases with permission errors
docker-compose exec -u 1002 -T spire-agent \
	/opt/spire/conf/agent/adminclient -expectErrors || fail-now "fail to check admin endpoints"
