#!/bin/bash

log-debug "Starting intermediateA-server.."
docker-up intermediateA-server

log-debug "bootstrapping intermediateA agent..."
docker-compose exec -T intermediateA-server \
    /opt/spire/bin/spire-server bundle show > intermediateA/agent/bootstrap.crt

log-debug "Starting intermediateA-agent..."
docker-up intermediateA-agent
