#!/bin/bash

log-debug "Starting intermediateB-server.."
docker-up intermediateB-server

log-debug "bootstrapping intermediateB downstream agent..."
docker-compose exec -T intermediateB-server \
    /opt/spire/bin/spire-server bundle show > intermediateB/agent/bootstrap.crt

log-debug "Starting intermediateB-agent..."
docker-up intermediateB-agent
