#!/bin/bash

log-debug "Starting leafB-server.."
docker-up leafB-server

log-debug "bootstrapping leafB agent..."
docker-compose exec -T leafB-server \
    /opt/spire/bin/spire-server bundle show > leafB/agent/bootstrap.crt

log-debug "Starting leafB-agent..."
docker-up leafB-agent
