// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package sri_proto is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	ConfigureRequest
	ConfigureResponse
	GetPluginInfoRequest
	GetPluginInfoResponse
	PluginInfoRequest
	PluginInfoReply
	StopRequest
	StopReply
*/
package sri_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// * Represents the plugin-specific configuration string.
type ConfigureRequest struct {
	Configuration string `protobuf:"bytes,1,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *ConfigureRequest) Reset()                    { *m = ConfigureRequest{} }
func (m *ConfigureRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigureRequest) ProtoMessage()               {}
func (*ConfigureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConfigureRequest) GetConfiguration() string {
	if m != nil {
		return m.Configuration
	}
	return ""
}

// * Represents a list of configuration problems found in the configuration string.
type ConfigureResponse struct {
	ErrorList []string `protobuf:"bytes,1,rep,name=errorList" json:"errorList,omitempty"`
}

func (m *ConfigureResponse) Reset()                    { *m = ConfigureResponse{} }
func (m *ConfigureResponse) String() string            { return proto.CompactTextString(m) }
func (*ConfigureResponse) ProtoMessage()               {}
func (*ConfigureResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConfigureResponse) GetErrorList() []string {
	if m != nil {
		return m.ErrorList
	}
	return nil
}

// * Represents an empty request.
type GetPluginInfoRequest struct {
}

func (m *GetPluginInfoRequest) Reset()                    { *m = GetPluginInfoRequest{} }
func (m *GetPluginInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPluginInfoRequest) ProtoMessage()               {}
func (*GetPluginInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// * Represents the plugin metadata.
type GetPluginInfoResponse struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Category    string `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
	Type        string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	DateCreated string `protobuf:"bytes,5,opt,name=dateCreated" json:"dateCreated,omitempty"`
	Location    string `protobuf:"bytes,6,opt,name=location" json:"location,omitempty"`
	Version     string `protobuf:"bytes,7,opt,name=version" json:"version,omitempty"`
	Author      string `protobuf:"bytes,8,opt,name=author" json:"author,omitempty"`
	Company     string `protobuf:"bytes,9,opt,name=company" json:"company,omitempty"`
}

func (m *GetPluginInfoResponse) Reset()                    { *m = GetPluginInfoResponse{} }
func (m *GetPluginInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPluginInfoResponse) ProtoMessage()               {}
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetPluginInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPluginInfoResponse) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *GetPluginInfoResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetPluginInfoResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetPluginInfoResponse) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func (m *GetPluginInfoResponse) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *GetPluginInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetPluginInfoResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *GetPluginInfoResponse) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type PluginInfoRequest struct {
}

func (m *PluginInfoRequest) Reset()                    { *m = PluginInfoRequest{} }
func (m *PluginInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*PluginInfoRequest) ProtoMessage()               {}
func (*PluginInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PluginInfoReply struct {
	PluginInfo []*GetPluginInfoResponse `protobuf:"bytes,1,rep,name=pluginInfo" json:"pluginInfo,omitempty"`
}

func (m *PluginInfoReply) Reset()                    { *m = PluginInfoReply{} }
func (m *PluginInfoReply) String() string            { return proto.CompactTextString(m) }
func (*PluginInfoReply) ProtoMessage()               {}
func (*PluginInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PluginInfoReply) GetPluginInfo() []*GetPluginInfoResponse {
	if m != nil {
		return m.PluginInfo
	}
	return nil
}

type StopRequest struct {
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type StopReply struct {
}

func (m *StopReply) Reset()                    { *m = StopReply{} }
func (m *StopReply) String() string            { return proto.CompactTextString(m) }
func (*StopReply) ProtoMessage()               {}
func (*StopReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*ConfigureRequest)(nil), "sri_proto.ConfigureRequest")
	proto.RegisterType((*ConfigureResponse)(nil), "sri_proto.ConfigureResponse")
	proto.RegisterType((*GetPluginInfoRequest)(nil), "sri_proto.GetPluginInfoRequest")
	proto.RegisterType((*GetPluginInfoResponse)(nil), "sri_proto.GetPluginInfoResponse")
	proto.RegisterType((*PluginInfoRequest)(nil), "sri_proto.PluginInfoRequest")
	proto.RegisterType((*PluginInfoReply)(nil), "sri_proto.PluginInfoReply")
	proto.RegisterType((*StopRequest)(nil), "sri_proto.StopRequest")
	proto.RegisterType((*StopReply)(nil), "sri_proto.StopReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Server service

type ServerClient interface {
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopReply, error)
	PluginInfo(ctx context.Context, in *PluginInfoRequest, opts ...grpc.CallOption) (*PluginInfoReply, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopReply, error) {
	out := new(StopReply)
	err := grpc.Invoke(ctx, "/sri_proto.Server/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) PluginInfo(ctx context.Context, in *PluginInfoRequest, opts ...grpc.CallOption) (*PluginInfoReply, error) {
	out := new(PluginInfoReply)
	err := grpc.Invoke(ctx, "/sri_proto.Server/PluginInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Server service

type ServerServer interface {
	Stop(context.Context, *StopRequest) (*StopReply, error)
	PluginInfo(context.Context, *PluginInfoRequest) (*PluginInfoReply, error)
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sri_proto.Server/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_PluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).PluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sri_proto.Server/PluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).PluginInfo(ctx, req.(*PluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sri_proto.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _Server_Stop_Handler,
		},
		{
			MethodName: "PluginInfo",
			Handler:    _Server_PluginInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common.proto",
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4f, 0xea, 0x40,
	0x10, 0xc7, 0x53, 0xe0, 0x15, 0x3a, 0x7d, 0xe4, 0x3d, 0x56, 0x24, 0x9b, 0x86, 0x43, 0xd3, 0x78,
	0xe0, 0x44, 0x22, 0x7a, 0xf0, 0x68, 0x42, 0xa2, 0x31, 0xf1, 0x60, 0xca, 0x07, 0x30, 0xb5, 0x0c,
	0xd8, 0xa4, 0xdd, 0x59, 0xb7, 0x5b, 0x92, 0x7e, 0x01, 0xfd, 0xda, 0xa6, 0xdb, 0x02, 0x55, 0xf4,
	0x36, 0xff, 0xdf, 0x7f, 0x66, 0xff, 0xbb, 0xb3, 0xf0, 0x37, 0xa6, 0x2c, 0x23, 0x31, 0x97, 0x8a,
	0x34, 0x31, 0x27, 0x57, 0xc9, 0xb3, 0x29, 0x83, 0x1b, 0xf8, 0xbf, 0x24, 0xb1, 0x49, 0xb6, 0x85,
	0xc2, 0x10, 0xdf, 0x0a, 0xcc, 0x35, 0xbb, 0x80, 0x61, 0xdc, 0xb0, 0x48, 0x27, 0x24, 0xb8, 0xe5,
	0x5b, 0x33, 0x27, 0xfc, 0x0a, 0x83, 0x4b, 0x18, 0xb5, 0x26, 0x73, 0x49, 0x22, 0x47, 0x36, 0x05,
	0x07, 0x95, 0x22, 0xf5, 0x98, 0xe4, 0x9a, 0x5b, 0x7e, 0x77, 0xe6, 0x84, 0x47, 0x10, 0x4c, 0x60,
	0x7c, 0x8f, 0xfa, 0x29, 0x2d, 0xb6, 0x89, 0x78, 0x10, 0x1b, 0x6a, 0x02, 0x83, 0x8f, 0x0e, 0x9c,
	0x7f, 0x33, 0x9a, 0xf3, 0x18, 0xf4, 0x44, 0x94, 0x61, 0x73, 0x03, 0x53, 0x33, 0x0f, 0x06, 0x71,
	0xa4, 0x71, 0x4b, 0xaa, 0xe4, 0x1d, 0xc3, 0x0f, 0xba, 0xea, 0xd7, 0xa5, 0x44, 0xde, 0xad, 0xfb,
	0xab, 0x9a, 0xf9, 0xe0, 0xae, 0x31, 0x8f, 0x55, 0x22, 0xcd, 0x63, 0x7a, 0xc6, 0x6a, 0x23, 0xd3,
	0x11, 0x69, 0x5c, 0x2a, 0x8c, 0x34, 0xae, 0xf9, 0x9f, 0xa6, 0xe3, 0x88, 0xaa, 0xcc, 0x94, 0xe2,
	0x7a, 0x1b, 0x76, 0x9d, 0xb9, 0xd7, 0x8c, 0x43, 0x7f, 0x87, 0x2a, 0xaf, 0xac, 0xbe, 0xb1, 0xf6,
	0x92, 0x4d, 0xc0, 0x8e, 0x0a, 0xfd, 0x4a, 0x8a, 0x0f, 0x8c, 0xd1, 0xa8, 0x6a, 0x22, 0xa6, 0x4c,
	0x46, 0xa2, 0xe4, 0x4e, 0x3d, 0xd1, 0xc8, 0xe0, 0x0c, 0x46, 0xa7, 0xeb, 0x59, 0xc1, 0xbf, 0x36,
	0x94, 0x69, 0xc9, 0x6e, 0x01, 0xe4, 0x01, 0x99, 0x45, 0xbb, 0x0b, 0x7f, 0x7e, 0xf8, 0xd6, 0xf9,
	0x8f, 0xdb, 0x0c, 0x5b, 0x33, 0xc1, 0x10, 0xdc, 0x95, 0x26, 0xb9, 0xcf, 0x70, 0xc1, 0xa9, 0xa5,
	0x4c, 0xcb, 0xc5, 0xbb, 0x05, 0xf6, 0x0a, 0xd5, 0x0e, 0x15, 0xbb, 0x86, 0x5e, 0xc5, 0xd9, 0xa4,
	0x75, 0x78, 0x6b, 0xce, 0x1b, 0x9f, 0xf0, 0xea, 0x7a, 0x77, 0x00, 0xc7, 0x78, 0x36, 0x6d, 0xf5,
	0x9c, 0xbc, 0xce, 0xf3, 0x7e, 0x71, 0x65, 0x5a, 0xbe, 0xd8, 0x06, 0x5f, 0x7d, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x9a, 0x85, 0xc6, 0x87, 0xbf, 0x02, 0x00, 0x00,
}
