#!/bin/bash

ENTRYCOUNT=12
CACHESIZE=8

docker-compose exec -u 1001 -T spire-agent \
  /opt/spire/bin/spire-agent api fetch x509 \
  -socketPath /opt/spire/sockets/workload_api.sock || fail-now "x509-SVID check failed"

# Call agent debug endpoints and check if svid count is equal number of entries registered
check-svid-count "spire-agent" $ENTRYCOUNT

# Call agent debug endpoints and check if svids from cache are cleaned up after expiry
check-svid-count "spire-agent" $CACHESIZE
