// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spiffe/spire/pkg/agent/cache (interfaces: Manager)

package mock_cache

import (
	gomock "github.com/golang/mock/gomock"
	cache "github.com/spiffe/spire/pkg/agent/cache"
	reflect "reflect"
)

// MockManager is a mock of Manager interface
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockManager) EXPECT() *MockManagerMockRecorder {
	return _m.recorder
}

// Cache mocks base method
func (_m *MockManager) Cache() cache.Cache {
	ret := _m.ctrl.Call(_m, "Cache")
	ret0, _ := ret[0].(cache.Cache)
	return ret0
}

// Cache indicates an expected call of Cache
func (_mr *MockManagerMockRecorder) Cache() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Cache", reflect.TypeOf((*MockManager)(nil).Cache))
}

// Done mocks base method
func (_m *MockManager) Done() <-chan struct{} {
	ret := _m.ctrl.Call(_m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done
func (_mr *MockManagerMockRecorder) Done() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Done", reflect.TypeOf((*MockManager)(nil).Done))
}

// Err mocks base method
func (_m *MockManager) Err() error {
	ret := _m.ctrl.Call(_m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err
func (_mr *MockManagerMockRecorder) Err() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Err", reflect.TypeOf((*MockManager)(nil).Err))
}

// Init mocks base method
func (_m *MockManager) Init() {
	_m.ctrl.Call(_m, "Init")
}

// Init indicates an expected call of Init
func (_mr *MockManagerMockRecorder) Init() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Init", reflect.TypeOf((*MockManager)(nil).Init))
}

// Shutdown mocks base method
func (_m *MockManager) Shutdown(_param0 error) {
	_m.ctrl.Call(_m, "Shutdown", _param0)
}

// Shutdown indicates an expected call of Shutdown
func (_mr *MockManagerMockRecorder) Shutdown(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Shutdown", reflect.TypeOf((*MockManager)(nil).Shutdown), arg0)
}
