#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PKGDIR="${REPODIR}/pkg/server/datastore"

log-debug "building postgres test harness..."
(cd "${PKGDIR}"; go test -c -o "${DIR}"/postgres.test -ldflags "-X github.com/spiffe/spire/pkg/server/datastore_test.TestDialect=postgres -X github.com/spiffe/spire/pkg/server/datastore_test.TestConnString=postgres://postgres:password@localhost:9999/postgres?sslmode=disable -X github.com/spiffe/spire/pkg/server/datastore_test.TestROConnString=postgres://postgres:password@localhost:9999/postgres?sslmode=disable")

log-debug "copying over test data..."
cp -r "${PKGDIR}"/testdata .
