#!/bin/bash

# 15 checks should be enough for the server to prepare and rotate into a new CA
# and mint a new SVID with the new CA.
NUMCHECKS=15
for ((i=1;i<=NUMCHECKS;i++)); do
    log-info "checking X509-SVID ($i of $NUMCHECKS)..."
    docker-compose exec spire-agent \
        /opt/spire/bin/spire-agent api fetch x509 || fail-now "SVID check failed"
    sleep 3
done

# rotation appears successful. touch the "success" file to pass the test.
touch success
