// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node_attestor.proto

/*
Package sri_proto is a generated protocol buffer package.

It is generated from these files:
	node_attestor.proto

It has these top-level messages:
	AttestedData
	AttestRequest
	AttestResponse
*/
package sri_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import sri_proto1 "github.com/spiffe/sri/control_plane/plugins/common/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ConfigureRequest from public import github.com/spiffe/sri/control_plane/plugins/common/proto/common.proto
type ConfigureRequest sri_proto1.ConfigureRequest

func (m *ConfigureRequest) Reset()         { (*sri_proto1.ConfigureRequest)(m).Reset() }
func (m *ConfigureRequest) String() string { return (*sri_proto1.ConfigureRequest)(m).String() }
func (*ConfigureRequest) ProtoMessage()    {}
func (m *ConfigureRequest) GetConfiguration() string {
	return (*sri_proto1.ConfigureRequest)(m).GetConfiguration()
}

// ConfigureResponse from public import github.com/spiffe/sri/control_plane/plugins/common/proto/common.proto
type ConfigureResponse sri_proto1.ConfigureResponse

func (m *ConfigureResponse) Reset()         { (*sri_proto1.ConfigureResponse)(m).Reset() }
func (m *ConfigureResponse) String() string { return (*sri_proto1.ConfigureResponse)(m).String() }
func (*ConfigureResponse) ProtoMessage()    {}
func (m *ConfigureResponse) GetErrorList() []string {
	return (*sri_proto1.ConfigureResponse)(m).GetErrorList()
}

// GetPluginInfoRequest from public import github.com/spiffe/sri/control_plane/plugins/common/proto/common.proto
type GetPluginInfoRequest sri_proto1.GetPluginInfoRequest

func (m *GetPluginInfoRequest) Reset()         { (*sri_proto1.GetPluginInfoRequest)(m).Reset() }
func (m *GetPluginInfoRequest) String() string { return (*sri_proto1.GetPluginInfoRequest)(m).String() }
func (*GetPluginInfoRequest) ProtoMessage()    {}

// GetPluginInfoResponse from public import github.com/spiffe/sri/control_plane/plugins/common/proto/common.proto
type GetPluginInfoResponse sri_proto1.GetPluginInfoResponse

func (m *GetPluginInfoResponse) Reset() { (*sri_proto1.GetPluginInfoResponse)(m).Reset() }
func (m *GetPluginInfoResponse) String() string {
	return (*sri_proto1.GetPluginInfoResponse)(m).String()
}
func (*GetPluginInfoResponse) ProtoMessage() {}
func (m *GetPluginInfoResponse) GetName() string {
	return (*sri_proto1.GetPluginInfoResponse)(m).GetName()
}
func (m *GetPluginInfoResponse) GetCategory() string {
	return (*sri_proto1.GetPluginInfoResponse)(m).GetCategory()
}
func (m *GetPluginInfoResponse) GetType() string {
	return (*sri_proto1.GetPluginInfoResponse)(m).GetType()
}
func (m *GetPluginInfoResponse) GetDescription() string {
	return (*sri_proto1.GetPluginInfoResponse)(m).GetDescription()
}
func (m *GetPluginInfoResponse) GetDateCreated() string {
	return (*sri_proto1.GetPluginInfoResponse)(m).GetDateCreated()
}
func (m *GetPluginInfoResponse) GetLocation() string {
	return (*sri_proto1.GetPluginInfoResponse)(m).GetLocation()
}
func (m *GetPluginInfoResponse) GetVersion() string {
	return (*sri_proto1.GetPluginInfoResponse)(m).GetVersion()
}
func (m *GetPluginInfoResponse) GetAuthor() string {
	return (*sri_proto1.GetPluginInfoResponse)(m).GetAuthor()
}
func (m *GetPluginInfoResponse) GetCompany() string {
	return (*sri_proto1.GetPluginInfoResponse)(m).GetCompany()
}

// *A type which contains attestation data for specific platform.
type AttestedData struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *AttestedData) Reset()                    { *m = AttestedData{} }
func (m *AttestedData) String() string            { return proto.CompactTextString(m) }
func (*AttestedData) ProtoMessage()               {}
func (*AttestedData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AttestedData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AttestedData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// *Represents a request to attest a node.
type AttestRequest struct {
	AttestedData   *AttestedData `protobuf:"bytes,1,opt,name=attestedData" json:"attestedData,omitempty"`
	AttestedBefore bool          `protobuf:"varint,2,opt,name=attestedBefore" json:"attestedBefore,omitempty"`
}

func (m *AttestRequest) Reset()                    { *m = AttestRequest{} }
func (m *AttestRequest) String() string            { return proto.CompactTextString(m) }
func (*AttestRequest) ProtoMessage()               {}
func (*AttestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AttestRequest) GetAttestedData() *AttestedData {
	if m != nil {
		return m.AttestedData
	}
	return nil
}

func (m *AttestRequest) GetAttestedBefore() bool {
	if m != nil {
		return m.AttestedBefore
	}
	return false
}

// *Represents a response when attesting a node.
type AttestResponse struct {
	Valid        bool   `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	BaseSPIFFEID string `protobuf:"bytes,2,opt,name=baseSPIFFEID" json:"baseSPIFFEID,omitempty"`
}

func (m *AttestResponse) Reset()                    { *m = AttestResponse{} }
func (m *AttestResponse) String() string            { return proto.CompactTextString(m) }
func (*AttestResponse) ProtoMessage()               {}
func (*AttestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AttestResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *AttestResponse) GetBaseSPIFFEID() string {
	if m != nil {
		return m.BaseSPIFFEID
	}
	return ""
}

func init() {
	proto.RegisterType((*AttestedData)(nil), "sri_proto.AttestedData")
	proto.RegisterType((*AttestRequest)(nil), "sri_proto.AttestRequest")
	proto.RegisterType((*AttestResponse)(nil), "sri_proto.AttestResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeAttestor service

type NodeAttestorClient interface {
	// *Responsible for configuration of the plugin.
	Configure(ctx context.Context, in *sri_proto1.ConfigureRequest, opts ...grpc.CallOption) (*sri_proto1.ConfigureResponse, error)
	// *Returns the  version and related metadata of the installed plugin.
	GetPluginInfo(ctx context.Context, in *sri_proto1.GetPluginInfoRequest, opts ...grpc.CallOption) (*sri_proto1.GetPluginInfoResponse, error)
	// *Attesta a node.
	Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestResponse, error)
}

type nodeAttestorClient struct {
	cc *grpc.ClientConn
}

func NewNodeAttestorClient(cc *grpc.ClientConn) NodeAttestorClient {
	return &nodeAttestorClient{cc}
}

func (c *nodeAttestorClient) Configure(ctx context.Context, in *sri_proto1.ConfigureRequest, opts ...grpc.CallOption) (*sri_proto1.ConfigureResponse, error) {
	out := new(sri_proto1.ConfigureResponse)
	err := grpc.Invoke(ctx, "/sri_proto.NodeAttestor/Configure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAttestorClient) GetPluginInfo(ctx context.Context, in *sri_proto1.GetPluginInfoRequest, opts ...grpc.CallOption) (*sri_proto1.GetPluginInfoResponse, error) {
	out := new(sri_proto1.GetPluginInfoResponse)
	err := grpc.Invoke(ctx, "/sri_proto.NodeAttestor/GetPluginInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAttestorClient) Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestResponse, error) {
	out := new(AttestResponse)
	err := grpc.Invoke(ctx, "/sri_proto.NodeAttestor/Attest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeAttestor service

type NodeAttestorServer interface {
	// *Responsible for configuration of the plugin.
	Configure(context.Context, *sri_proto1.ConfigureRequest) (*sri_proto1.ConfigureResponse, error)
	// *Returns the  version and related metadata of the installed plugin.
	GetPluginInfo(context.Context, *sri_proto1.GetPluginInfoRequest) (*sri_proto1.GetPluginInfoResponse, error)
	// *Attesta a node.
	Attest(context.Context, *AttestRequest) (*AttestResponse, error)
}

func RegisterNodeAttestorServer(s *grpc.Server, srv NodeAttestorServer) {
	s.RegisterService(&_NodeAttestor_serviceDesc, srv)
}

func _NodeAttestor_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sri_proto1.ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAttestorServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sri_proto.NodeAttestor/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAttestorServer).Configure(ctx, req.(*sri_proto1.ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAttestor_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sri_proto1.GetPluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAttestorServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sri_proto.NodeAttestor/GetPluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAttestorServer).GetPluginInfo(ctx, req.(*sri_proto1.GetPluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAttestor_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAttestorServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sri_proto.NodeAttestor/Attest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAttestorServer).Attest(ctx, req.(*AttestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeAttestor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sri_proto.NodeAttestor",
	HandlerType: (*NodeAttestorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _NodeAttestor_Configure_Handler,
		},
		{
			MethodName: "GetPluginInfo",
			Handler:    _NodeAttestor_GetPluginInfo_Handler,
		},
		{
			MethodName: "Attest",
			Handler:    _NodeAttestor_Attest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node_attestor.proto",
}

func init() { proto.RegisterFile("node_attestor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4e, 0xe3, 0x30,
	0x10, 0x86, 0x37, 0xab, 0xdd, 0xaa, 0x99, 0x4d, 0x7b, 0xf0, 0x22, 0x51, 0x0a, 0x12, 0x55, 0x0e,
	0xa8, 0xa7, 0x44, 0x2a, 0x12, 0x17, 0xc4, 0xa1, 0xd0, 0x16, 0x95, 0x03, 0xaa, 0xcc, 0x03, 0x54,
	0x6e, 0x33, 0x29, 0x96, 0x52, 0x4f, 0xb0, 0x1d, 0x24, 0x1e, 0x99, 0xb7, 0x40, 0x38, 0x49, 0x95,
	0x42, 0xb9, 0x79, 0xfe, 0x99, 0xf9, 0xfe, 0xdf, 0x03, 0xff, 0x15, 0x25, 0xb8, 0x14, 0xd6, 0xa2,
	0xb1, 0xa4, 0xa3, 0x5c, 0x93, 0x25, 0xe6, 0x1b, 0x2d, 0x97, 0xee, 0xd9, 0x9f, 0x6e, 0xa4, 0x7d,
	0x2e, 0x56, 0xd1, 0x9a, 0xb6, 0xb1, 0xc9, 0x65, 0x9a, 0x62, 0x6c, 0xb4, 0x8c, 0xd7, 0xa4, 0xac,
	0xa6, 0x6c, 0x99, 0x67, 0x42, 0x61, 0x9c, 0x67, 0xc5, 0x46, 0x2a, 0x13, 0xaf, 0x69, 0xbb, 0x25,
	0x15, 0xbb, 0xcd, 0xaa, 0x28, 0x89, 0xe1, 0x15, 0x04, 0x63, 0xe7, 0x81, 0xc9, 0x44, 0x58, 0xc1,
	0x18, 0xfc, 0xb1, 0x6f, 0x39, 0xf6, 0xbc, 0x81, 0x37, 0xf4, 0xb9, 0x7b, 0x7f, 0x6a, 0x89, 0xb0,
	0xa2, 0xf7, 0x7b, 0xe0, 0x0d, 0x03, 0xee, 0xde, 0xa1, 0x85, 0x4e, 0xb9, 0xc7, 0xf1, 0xa5, 0x40,
	0x63, 0xd9, 0x35, 0x04, 0xa2, 0x01, 0x72, 0x80, 0x7f, 0xa3, 0xe3, 0x68, 0x97, 0x38, 0x6a, 0xfa,
	0xf0, 0xbd, 0x61, 0x76, 0x01, 0xdd, 0xba, 0xbe, 0xc5, 0x94, 0x34, 0x3a, 0xaf, 0x36, 0xff, 0xa2,
	0x86, 0x0f, 0xd0, 0xad, 0x5d, 0x4d, 0x4e, 0xca, 0x20, 0x3b, 0x82, 0xbf, 0xaf, 0x22, 0x93, 0x89,
	0xf3, 0x6b, 0xf3, 0xb2, 0x60, 0x21, 0x04, 0x2b, 0x61, 0xf0, 0x69, 0x31, 0x9f, 0xcd, 0xa6, 0xf3,
	0x89, 0xa3, 0xf9, 0x7c, 0x4f, 0x1b, 0xbd, 0x7b, 0x10, 0x3c, 0x52, 0x82, 0xe3, 0xea, 0xc4, 0x6c,
	0x06, 0xfe, 0x1d, 0xa9, 0x54, 0x6e, 0x0a, 0x8d, 0xec, 0xb4, 0x11, 0x7c, 0xa7, 0x56, 0x7f, 0xed,
	0x9f, 0x1d, 0x6e, 0x56, 0x91, 0x38, 0x74, 0xee, 0xd1, 0x2e, 0xdc, 0xe9, 0xe7, 0x2a, 0x25, 0x76,
	0xde, 0x18, 0xdf, 0xeb, 0xd4, 0xbc, 0xc1, 0xcf, 0x03, 0x15, 0xf3, 0x06, 0x5a, 0x65, 0x4e, 0xd6,
	0xfb, 0x76, 0xd1, 0x9a, 0x72, 0x72, 0xa0, 0x53, 0xae, 0x2f, 0x7e, 0xad, 0x5a, 0x4e, 0xbf, 0xfc,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x38, 0x24, 0xd5, 0x57, 0x02, 0x00, 0x00,
}
