// Code generated by protoc-gen-go. DO NOT EDIT.
// source: upstream_ca.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	upstream_ca.proto

It has these top-level messages:
	SubmitCSRRequest
	SubmitCSRResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type SubmitCSRRequest struct {
	Csr []byte `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
}

func (m *SubmitCSRRequest) Reset()                    { *m = SubmitCSRRequest{} }
func (m *SubmitCSRRequest) String() string            { return proto1.CompactTextString(m) }
func (*SubmitCSRRequest) ProtoMessage()               {}
func (*SubmitCSRRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SubmitCSRRequest) GetCsr() []byte {
	if m != nil {
		return m.Csr
	}
	return nil
}

type SubmitCSRResponse struct {
	Cert                []byte `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	UpstreamTrustBundle []byte `protobuf:"bytes,2,opt,name=upstreamTrustBundle,proto3" json:"upstreamTrustBundle,omitempty"`
}

func (m *SubmitCSRResponse) Reset()                    { *m = SubmitCSRResponse{} }
func (m *SubmitCSRResponse) String() string            { return proto1.CompactTextString(m) }
func (*SubmitCSRResponse) ProtoMessage()               {}
func (*SubmitCSRResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubmitCSRResponse) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *SubmitCSRResponse) GetUpstreamTrustBundle() []byte {
	if m != nil {
		return m.UpstreamTrustBundle
	}
	return nil
}

func init() {
	proto1.RegisterType((*SubmitCSRRequest)(nil), "proto.SubmitCSRRequest")
	proto1.RegisterType((*SubmitCSRResponse)(nil), "proto.SubmitCSRResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	SubmitCSR(ctx context.Context, in *SubmitCSRRequest, opts ...grpc.CallOption) (*SubmitCSRResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) SubmitCSR(ctx context.Context, in *SubmitCSRRequest, opts ...grpc.CallOption) (*SubmitCSRResponse, error) {
	out := new(SubmitCSRResponse)
	err := grpc.Invoke(ctx, "/proto.node/SubmitCSR", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	SubmitCSR(context.Context, *SubmitCSRRequest) (*SubmitCSRResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_SubmitCSR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCSRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SubmitCSR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.node/SubmitCSR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SubmitCSR(ctx, req.(*SubmitCSRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitCSR",
			Handler:    _Node_SubmitCSR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "upstream_ca.proto",
}

func init() { proto1.RegisterFile("upstream_ca.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2d, 0x28, 0x2e,
	0x29, 0x4a, 0x4d, 0xcc, 0x8d, 0x4f, 0x4e, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x4a, 0x2a, 0x5c, 0x02, 0xc1, 0xa5, 0x49, 0xb9, 0x99, 0x25, 0xce, 0xc1, 0x41, 0x41, 0xa9,
	0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x02, 0x5c, 0xcc, 0xc9, 0xc5, 0x45, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x3c, 0x41, 0x20, 0xa6, 0x52, 0x24, 0x97, 0x20, 0x92, 0xaa, 0xe2, 0x82, 0xfc, 0xbc, 0xe2,
	0x54, 0x21, 0x21, 0x2e, 0x96, 0xe4, 0xd4, 0xa2, 0x12, 0xa8, 0x3a, 0x30, 0x5b, 0xc8, 0x80, 0x4b,
	0x18, 0x66, 0x55, 0x48, 0x51, 0x69, 0x71, 0x89, 0x53, 0x69, 0x5e, 0x4a, 0x4e, 0xaa, 0x04, 0x13,
	0x58, 0x09, 0x36, 0x29, 0x23, 0x37, 0x2e, 0x96, 0xbc, 0xfc, 0x94, 0x54, 0x21, 0x3b, 0x2e, 0x4e,
	0xb8, 0x15, 0x42, 0xe2, 0x10, 0x47, 0xea, 0xa1, 0x3b, 0x4d, 0x4a, 0x02, 0x53, 0x02, 0xe2, 0x9a,
	0x24, 0x36, 0xb0, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x40, 0x9e, 0xb4, 0xe9, 0xeb, 0x00,
	0x00, 0x00,
}
