#!/bin/bash

# Create a temporary path that will be added to the PATH to avoid picking up
# binaries from the environment that aren't a version match.
mkdir -p ./bin

KIND_PATH=./bin/kind
KUBECTL_PATH=./bin/kubectl

# Download kind at the expected version at the given path.
download-kind "${KIND_PATH}"

# Download kubectl at the expected version.
download-kubectl "${KUBECTL_PATH}"

# We must supply an absolute path to the configuration directory. Replace the
# CONFDIR variable in the kind configuration with the conf directory of the 
# running test.
sed -i.bak "s#CONFDIR#${PWD}/conf#g" conf/kind-config.yaml
rm conf/kind-config.yaml.bak

# Start the kind cluster.
start-kind-cluster "${KIND_PATH}" k8stest ./conf/kind-config.yaml

# Load the given images in the cluster.
container_images=("spire-server-scratch:latest-local" "spire-agent-scratch:latest-local" "k8s-workload-registrar-scratch:latest-local")
load-images "${KIND_PATH}" k8stest "${container_images[@]}"

# Set the kubectl context.
set-kubectl-context "${KUBECTL_PATH}" kind-k8stest
