#!/bin/bash
echo ${ROOTDIR}

"${ROOTDIR}/setup/x509pop/setup.sh" conf/server conf/agent conf/
# Move test x509pop certificate and key
mv conf/agent.key.pem conf/agent/test.key.pem
mv conf/agent.crt.pem conf/agent/test.crt.pem

"${ROOTDIR}/setup/node-attestation/build.sh" "${RUNDIR}/conf/server/node-attestation"
"${ROOTDIR}/setup/node-attestation/build.sh" "${RUNDIR}/conf/agent/node-attestation"

