#!/bin/bash

KUBECTLPATH=$(command -v kubectl || echo)
KINDPATH=$(command -v kind || echo)

UNAME=$(uname | awk '{print tolower($0)}')

KINDVERSION=v0.11.1
KINDURL="https://github.com/kubernetes-sigs/kind/releases/download/$KINDVERSION/kind-$UNAME-amd64"
KUBECTLVERSION=v1.21.1
KUBECTLURL="https://storage.googleapis.com/kubernetes-release/release/$KUBECTLVERSION/bin/$UNAME/amd64/kubectl"

# Create a temporary path that will be added to the PATH to avoid picking up
# binaries from the environment that aren't a version match.
mkdir -p ./bin

download_bin() {
    local bin_path=$1
    local bin_url=$2
    if [ ! -f "${bin_path}" ] ; then
        log-info "downloading $(basename ${bin_path}) from ${bin_url}..."
        curl -# -f -Lo "${bin_path}" "${bin_url}"
        chmod +x "${bin_path}"
    fi
}

# Ensure kind exists at the expected version
if [ -x "${KINDPATH}" ] && "${KINDPATH}" version | grep -q "${KINDVERSION}"; then
    ln -s "${KINDPATH}" ./bin/kind
else
    download_bin ./bin/kind "${KINDURL}"
fi

# Ensure kubectl exists at the expected version
if [ -x "${KUBECTLPATH}" ] && "${KUBECTLPATH}" version --short --client=true | grep -q "${KUBECTLVERSION}"; then
    ln -s "${KUBECTLPATH}" ./bin/kubectl
else
    download_bin ./bin/kubectl "${KUBECTLURL}"
fi

# We must supply an absolute path to the configuration directory. Replace the
# CONFDIR variable in the kind configuration with the conf directory of the 
# running test.
sed -i.bak "s#CONFDIR#${PWD}/conf#g" conf/kind-config.yaml
rm conf/kind-config.yaml.bak

log-info "starting cluster..."
./bin/kind create cluster --name k8stest --config ./conf/kind-config.yaml || fail-now "unable to create cluster"

log-info "loading container images..."
./bin/kind load docker-image --name k8stest spire-server-scratch:latest-local
./bin/kind load docker-image --name k8stest spire-agent-scratch:latest-local
./bin/kind load docker-image --name k8stest k8s-workload-registrar-scratch:latest-local

log-info "setting kubectl cluster context..."
./bin/kubectl cluster-info --context kind-k8stest
