#!/bin/bash

# Verify 3 agents were created
listResult="$(docker-compose exec -T spire-server \
    /opt/spire/bin/spire-server agent list)"

echo "$listResult" | grep "Found 3 attested agents" || fail-now "failed to list the 3 agents initially"
echo "$listResult" | grep "Attestation type" | grep "join_token" || fail-now "unexpected agents attestation type"

# Get agent SPIFFE IDs from entries, knowing they were attested using join-token
# Agent 1
agentID1="$(docker-compose exec -T spire-server \
	/opt/spire/bin/spire-server entry show \
    -spiffeID spiffe://domain.test/node1)"
agentID1="$(echo "$agentID1" | grep "Parent ID")" || fail-now "failed to extract agentID1"
agentID1="${agentID1#*: }"

# Agent 2
agentID2="$(docker-compose exec -T spire-server \
	/opt/spire/bin/spire-server entry show \
    -spiffeID spiffe://domain.test/node2)"
agentID2="$(echo "$agentID2" | grep "Parent ID")" || fail-now "failed to extract agentID2"
agentID2="${agentID2#*: }"

# Agent 3
agentID3="$(docker-compose exec -T spire-server \
	/opt/spire/bin/spire-server entry show \
    -spiffeID spiffe://domain.test/node3)"
agentID3="$(echo "$agentID3" | grep "Parent ID")" || fail-now "failed to extract agentID3"
agentID3="${agentID3#*: }"

# Verify agentIDs match
echo "$listResult" | grep "$agentID1" || fail-now "agentID1=$agentID1 not found in agentIDs list"
echo "$listResult" | grep "$agentID2" || fail-now "agentID2=$agentID2 not found in agentIDs list"
echo "$listResult" | grep "$agentID3" || fail-now "agentID3=$agentID3 not found in agentIDs list"
