// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins/node_resolution/proto/node_resolution.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	plugins/node_resolution/proto/node_resolution.proto

It has these top-level messages:
	NodeResolution
	NodeResolutionList
	ResolveRequest
	ResolveResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeResolution struct {
	SelectorType string `protobuf:"bytes,1,opt,name=selectorType" json:"selectorType,omitempty"`
	Selector     string `protobuf:"bytes,2,opt,name=selector" json:"selector,omitempty"`
}

func (m *NodeResolution) Reset()                    { *m = NodeResolution{} }
func (m *NodeResolution) String() string            { return proto1.CompactTextString(m) }
func (*NodeResolution) ProtoMessage()               {}
func (*NodeResolution) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeResolution) GetSelectorType() string {
	if m != nil {
		return m.SelectorType
	}
	return ""
}

func (m *NodeResolution) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

type NodeResolutionList struct {
	List []*NodeResolution `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *NodeResolutionList) Reset()                    { *m = NodeResolutionList{} }
func (m *NodeResolutionList) String() string            { return proto1.CompactTextString(m) }
func (*NodeResolutionList) ProtoMessage()               {}
func (*NodeResolutionList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeResolutionList) GetList() []*NodeResolution {
	if m != nil {
		return m.List
	}
	return nil
}

type ResolveRequest struct {
	PhysicalSpiffeIdList []string `protobuf:"bytes,1,rep,name=physicalSpiffeIdList" json:"physicalSpiffeIdList,omitempty"`
}

func (m *ResolveRequest) Reset()                    { *m = ResolveRequest{} }
func (m *ResolveRequest) String() string            { return proto1.CompactTextString(m) }
func (*ResolveRequest) ProtoMessage()               {}
func (*ResolveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResolveRequest) GetPhysicalSpiffeIdList() []string {
	if m != nil {
		return m.PhysicalSpiffeIdList
	}
	return nil
}

type ResolveResponse struct {
	Map map[string]*NodeResolutionList `protobuf:"bytes,1,rep,name=map" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ResolveResponse) Reset()                    { *m = ResolveResponse{} }
func (m *ResolveResponse) String() string            { return proto1.CompactTextString(m) }
func (*ResolveResponse) ProtoMessage()               {}
func (*ResolveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResolveResponse) GetMap() map[string]*NodeResolutionList {
	if m != nil {
		return m.Map
	}
	return nil
}

func init() {
	proto1.RegisterType((*NodeResolution)(nil), "proto.NodeResolution")
	proto1.RegisterType((*NodeResolutionList)(nil), "proto.NodeResolutionList")
	proto1.RegisterType((*ResolveRequest)(nil), "proto.ResolveRequest")
	proto1.RegisterType((*ResolveResponse)(nil), "proto.ResolveResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	out := new(ResolveResponse)
	err := grpc.Invoke(ctx, "/proto.node/Resolve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.node/Resolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _Node_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins/node_resolution/proto/node_resolution.proto",
}

func init() {
	proto1.RegisterFile("plugins/node_resolution/proto/node_resolution.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0xfe, 0x81, 0xf6, 0x8a, 0x0a, 0x3a, 0x51, 0x54, 0xba, 0x50, 0x65, 0x2a, 0x4b,
	0x22, 0xd2, 0xa5, 0x62, 0x81, 0x01, 0x06, 0xa4, 0x82, 0xc0, 0xb0, 0xa3, 0xd0, 0x5c, 0xc1, 0xc2,
	0xc4, 0x26, 0x76, 0x2a, 0xe5, 0x93, 0xf0, 0x75, 0x51, 0xdc, 0x24, 0x52, 0xa2, 0x4c, 0xf6, 0xbd,
	0x7b, 0x7a, 0xfe, 0xdd, 0x19, 0x96, 0x4a, 0xa4, 0x9f, 0x3c, 0xd6, 0x7e, 0x2c, 0x23, 0x7a, 0x4f,
	0x48, 0x4b, 0x91, 0x1a, 0x2e, 0x63, 0x5f, 0x25, 0xd2, 0xc8, 0xa6, 0xea, 0x59, 0x15, 0xfb, 0xf6,
	0x70, 0x9f, 0x61, 0xfc, 0x24, 0x23, 0x62, 0x55, 0x1b, 0x5d, 0x38, 0xd2, 0x24, 0x68, 0x63, 0x64,
	0xf2, 0x96, 0x29, 0x9a, 0x3a, 0x73, 0x67, 0x31, 0x64, 0x35, 0x0d, 0x67, 0x30, 0x28, 0xeb, 0x69,
	0xc7, 0xf6, 0xab, 0xda, 0xbd, 0x01, 0xac, 0x27, 0xae, 0xb9, 0x36, 0x78, 0x09, 0x3d, 0xc1, 0xb5,
	0x99, 0x3a, 0xf3, 0xee, 0x62, 0x14, 0x4c, 0xf6, 0x10, 0x5e, 0xdd, 0xc8, 0xac, 0xc5, 0xbd, 0x83,
	0xb1, 0xd5, 0x76, 0xc4, 0xe8, 0x37, 0x25, 0x6d, 0x30, 0x80, 0x53, 0xf5, 0x95, 0x69, 0xbe, 0x09,
	0xc5, 0xab, 0xe2, 0xdb, 0x2d, 0x3d, 0x44, 0xeb, 0x32, 0x6c, 0xc8, 0x5a, 0x7b, 0xee, 0x9f, 0x03,
	0xc7, 0x55, 0x8c, 0x56, 0x32, 0xd6, 0x84, 0x57, 0xd0, 0xfd, 0x09, 0x55, 0xc1, 0x70, 0x51, 0x30,
	0x34, 0x4c, 0xde, 0x63, 0xa8, 0xee, 0x63, 0x93, 0x64, 0x2c, 0xf7, 0xce, 0x5e, 0x60, 0x50, 0x0a,
	0x78, 0x02, 0xdd, 0x6f, 0xca, 0x8a, 0x85, 0xe4, 0x57, 0xf4, 0xa1, 0xbf, 0x0b, 0x45, 0x4a, 0x76,
	0x09, 0xa3, 0xe0, 0xbc, 0x75, 0xac, 0x1c, 0x87, 0xed, 0x7d, 0xd7, 0x9d, 0x95, 0x13, 0xdc, 0x42,
	0x2f, 0xff, 0x12, 0x5c, 0xc1, 0x61, 0xf1, 0x36, 0x4e, 0x9a, 0x2c, 0x76, 0xee, 0xd9, 0x59, 0x3b,
	0xe2, 0xc7, 0x81, 0x95, 0x97, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x56, 0xc1, 0x8b, 0x02, 0xf9,
	0x01, 0x00, 0x00,
}
