#!/bin/bash

"${ROOTDIR}/setup/x509pop/setup.sh" conf/server conf/agent

"${ROOTDIR}/setup/svidstore/check/build.sh" "${RUNDIR}/conf/server/checkstoredsvids"

"${ROOTDIR}/setup/svidstore/plugin/build.sh" "${RUNDIR}/conf/agent/disk-plugin"
