#!/bin/bash

# Get the container for use with "docker exec" so we don't have the
# "docker-compose exec" startup time throwing off timing.
AGENTCONTAINER=$(docker-compose ps -q spire-agent)

# 75 seconds should be enough for the server to prepare and rotate into a new
# CA and mint a new SVID with the new CA a few times. Check every five seconds
# that the SVID is valid.
NUMCHECKS=15
CHECKINTERVAL=5
for ((i=1;i<=NUMCHECKS;i++)); do
    log-info "checking X509-SVID ($i of $NUMCHECKS)..."
    docker exec "${AGENTCONTAINER}" \
        /opt/spire/bin/spire-agent api fetch x509 || fail-now "SVID check failed"
    sleep "${CHECKINTERVAL}"
done
