#!/bin/bash

log-debug "bootstrapping agent..."
docker compose exec -T spire-server \
    /opt/spire/bin/spire-server bundle show > conf/agent/bootstrap.crt

log-debug "starting agent..."
docker-up spire-agent
