#!/bin/bash

source init-kubectl

if [ -z "$SUCCESS" ]; then
    ./bin/kubectl -nspire logs deployment/spire-server --all-containers || true
    ./bin/kubectl -nspire logs daemonset/spire-agent --all-containers || true
    for pod in broker cluster-broker agent-node-broker restricted-broker rbac-denied-broker unauthorized-workload target-pod same-node-target-pod other-node-target-pod; do
        ./bin/kubectl -nspire logs "pod/${pod}" --all-containers || true
        ./bin/kubectl -nspire describe "pod/${pod}" || true
    done
fi

export KUBECONFIG=
./bin/kind delete cluster --name broker-api-k8s
