#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PKGDIR="${REPODIR}/pkg/server/plugin/datastore/sql"

log-debug "building mysql test harness..."
(cd ${PKGDIR}; go test -c -o "${DIR}"/mysql.test -ldflags "-X github.com/spiffe/spire/pkg/server/plugin/datastore/sql.TestDialect=mysql -X github.com/spiffe/spire/pkg/server/plugin/datastore/sql.TestConnString=spire:test@tcp(localhost:9999)/spire?parseTime=true")

log-debug "copying over test data..."
cp -r "${PKGDIR}"/testdata .
