#!/bin/bash

source init-kubectl

if [ -z "$SUCCESS" ]; then
   ./bin/kubectl -nspire logs deployment/spire-server --all-containers || true
fi

export KUBECONFIG=
./bin/kind delete cluster --name ejbca-test
