#!/bin/bash

mkdir -p ./bin

KIND_PATH=./bin/kind
KUBECTL_PATH=./bin/kubectl

download-kind "${KIND_PATH}"
download-kubectl "${KUBECTL_PATH}"

start-kind-cluster "${KIND_PATH}" kmip-km

container_images=("spire-server:latest-local" "ghcr.io/cosmian/kms:5.26.0")
load-images "${KIND_PATH}" kmip-km "${container_images[@]}"

log-info "kind cluster 'kmip-km' ready with SPIRE and KMS images loaded"
