#!/bin/bash

source init-kubectl

if [ -z "$SUCCESS" ]; then
    for pod in $(./bin/kubectl -n spire get pods -o jsonpath='{.items[*].metadata.name}'); do
        echo "=== Logs for pod $pod ==="
        ./bin/kubectl -n spire logs "$pod" || true
    done
    ./bin/kubectl -n spire-test logs deployment/kmip-server --all-containers || true
fi

export KUBECONFIG=
./bin/kind delete cluster --name kmip-km
