#!/bin/bash

"${ROOTDIR}/setup/x509pop/setup.sh" conf/server conf/upstream-agent conf/downstream-agent

LATEST_ENVOY_RELEASE="$(basename "$(curl -Ls -o /dev/null -w "%{url_effective}" "https://github.com/envoyproxy/envoy/releases/latest")")"

cat > Dockerfile <<EOF
FROM spire-agent:latest-local as spire-agent

FROM envoyproxy/envoy-alpine:${LATEST_ENVOY_RELEASE} AS envoy-agent-mashup
COPY --from=spire-agent /opt/spire/bin/spire-agent /opt/spire/bin/spire-agent
RUN apk --no-cache add dumb-init
RUN apk --no-cache add supervisor
COPY conf/supervisord.conf /etc/
ENTRYPOINT ["/usr/bin/dumb-init", "supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf"]
CMD []
EOF

docker build --target envoy-agent-mashup -t envoy-agent-mashup .
