name: Nightly Build
on:
  schedule:
    # Random minute number to avoid GH scheduler stampede
    - cron: '37 21 * * *'
  workflow_dispatch: {}

env:
  NIGHTLY: true

jobs:
  build-and-publish-images:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install cosign
        uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0
        with:
          cosign-release: v2.6.2
      - name: Install regctl
        uses: regclient/actions/regctl-installer@9f6c88d6bc9e9d8416282b1f88be43758b0d066a # main
      - name: Build images
        run: make images
      - name: Log in to GHCR
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images
        run: ./.github/workflows/scripts/push-images.sh nightly
